defaultLanguage: en

#This prefix is for console logs
Prefix: "$4[$0%PluginName%$4] $2\xbb"

ColorCharacter: "$"
PluginColors:
- '3' #0
- 'b' #1
- '7' #2
- '8' #3
- 'f' #4
- 'l' #5
- 'm' #6