defaultLanguage: en

#This prefix is for console logs
Prefix: "$4[$0%PluginName%$4] $2\xbb"

ColorCharacter: "$"
PluginColors:
- '3' #0
- 'b' #1
- '9' #2
- '7' #3
- '8' #4
- 'f' #5
- 'l' #6
- 'm' #7
- 'a' #8
- 'c' #9